language: ru
recipe: default.v1

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 2
  - name: DIETClassifier
    epochs: 100
  - name: RegexEntityExtractor
    patterns:
      - pattern: "Расскажи мне о ([A-Za-z]+)"
      - pattern: "Расскажи мне про ([A-Za-z]+)"

  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-cased"
    cache_dir: null


    transformer_size: 256
    number_of_transformer_layers: 2
    use_masked_language_model: false
    batch_strategy: "balanced"
    hidden_layers_sizes:
      text: [256, 128]


  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 20

policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
  - name: TEDPolicy
    constrain_similarities: true
    max_history: 5
    epochs: 100
assistant_id: 20250221-175255-clean-citadel
