FROM node:18-slim AS build

ENV NODE_ENV development

ARG RASA_URL=http://localhost:5005

WORKDIR /app

COPY package.json package.json

RUN --mount=type=cache,target=/app/node_modules \
    yarn

COPY public public
COPY src src

ENV REACT_APP_RASA_URL=$RASA_URL

RUN --mount=type=cache,target=/app/node_modules \
    yarn build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80