FROM khalosa/rasa-aarch64:3.5.2

# отдельно потому что по новой ждать выкачивание этих жирных зависимостей лень
RUN pip install rasa[transformers]
RUN pip install rasa[spacy]
RUN python -m spacy download ru_core_news_sm

ENV LD_PRELOAD=/opt/venv/lib/python3.10/site-packages/scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
